version: "3"

services:
#################### content registry ######################
  content-api:
    image: mlexchange1/content-api:1.2
    restart: "unless-stopped"
    container_name: "content-api"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
#       ATLAS_ACCESS: '${ATLAS_USER}'
    ports:
      - "8000:8000"
    networks:
      - computing_api_default

  content-registry:
    image: mlexchange1/content-registry:1.4
    restart: "unless-stopped"
    container_name: "content-registry"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
      # ATLAS_ACCESS: '${ATLAS_USER}'
      CONTAINER_WORKING_DIR: '${PWD}/../data'
    ports:
      - "8051:8051"
    networks:
      - computing_api_default  

networks:
  computing_api_default:
    external: true

